plugins:
  topic_custom_field_enabled: 
    default: true
    client: true
  topic_custom_field_name:  
    default: 'rtopicinfo'
    client: true
  topic_custom_field_type: 
    default: 'json'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json